spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123
  aop:
    proxy-target-class: false
server:
  port: 8888
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
mybatis:
  mapper-locations: com/baizhi/kyh/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.kyh.enity
